INSERT INTO USERS(EMAIL, NAME, PASSWORD, ROLE) VALUES('Chorri777@gmail.com','Juan Costa Jose Maria', 'coco', 'Admin');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, ROLE) VALUES('Protoxxx@gmail.com','Adrian Gabriel Suarez', 'coca','Admin');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, ROLE) VALUES('CarlosUpa@gmail.com','Carlos Iparraguirre', 'cucu','Admin');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, ROLE) VALUES('sos@gmail.com','Hernan Razo', 'cici','Cliente');

INSERT INTO BRANDS(NAME) VALUES ('Levi')
INSERT INTO BRANDS(NAME) VALUES ('Hugo Boss')
INSERT INTO BRANDS(NAME) VALUES ('Adidas')


INSERT INTO BRANDS(NAME) VALUES ('ERB')

INSERT INTO MODELS(NAME, BRAND_ID) VALUES ('Levi', 1)
INSERT INTO MODELS(NAME, BRAND_ID) VALUES ('Hugo', 2)
INSERT INTO MODELS(NAME, BRAND_ID) VALUES ('15160', 4)
INSERT INTO MODELS(NAME, BRAND_ID) VALUES ('asdasd', 3)

INSERT INTO PRODUCTS(CATEGORY, DESCRIPTION, NAME, PRICE, STOCK, MODELO_ID) VALUES('Traje_Anti_Fluido', 'a', 'd', 80, 5, 4);
INSERT INTO PRODUCTS(CATEGORY, DESCRIPTION, NAME, PRICE, STOCK, MODELO_ID) VALUES('Protector_Facial', 'Mascara de protección facial', 'Hecho de policarbonato transparente', 10.0, 3, 3);
INSERT INTO PRODUCTS(CATEGORY, DESCRIPTION, NAME, PRICE, STOCK, MODELO_ID) VALUES('Mascarilla', 'Cubrebocas de tela color azul', 'Mascarilla Levi', 30.0, 6, 1);
INSERT INTO PRODUCTS(CATEGORY, DESCRIPTION, NAME, PRICE, STOCK, MODELO_ID) VALUES('Mascarilla', 'Cubrebocas unisex de algodon elastico con franja y logo', 'Mascarilla Hugo Boss', 50.0, 6, 2);


INSERT INTO ORDERS(STATUS, PAYMENT, REG_DATE, TOTAL) VALUES (TRUE , 'TARJETA', now(), 90);
INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, PRICE, QUANTITY, TOTAL) VALUES (1, 1, 80, 1, 80);
INSERT INTO ORDER_LINES(ORDER_ID, PRODUCT_ID, PRICE, QUANTITY, TOTAL) VALUES (1, 2, 10, 1, 10);

INSERT INTO IMAGES(PATH, PRODUCTO_ID) VALUES ('https://i.pinimg.com/originals/80/75/7f/80757fb419f1c394946a1b69dc0b075d.png', 3)
INSERT INTO IMAGES(PATH, PRODUCTO_ID) VALUES ('link traje antifluido', 1)
INSERT INTO IMAGES(PATH, PRODUCTO_ID) VALUES ('https://m.media-amazon.com/images/I/41D542x5oZL.jpg', 2)
INSERT INTO IMAGES(PATH, PRODUCTO_ID) VALUES ('https://images.hugoboss.com/is/image/boss/hbeu50452683_001_200?wid=688', 4)

INSERT INTO COMMENTS(DESCRIPTION, RATING, PRODUCTO_ID, USUARIO_ID) VALUES ('Mis dieces', 5, 1, 1)